package com.cyrene.conversation

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.Table
import java.time.OffsetDateTime

/**
 * Cached per-(user, guild) profile. Populated from JDA on first mention and refreshed
 * by [UserInfoRefreshScheduler] on a daily cadence.
 *
 * Permission flags here are advisory only — destructive moderation tools in
 * [com.cyrene.discord.tools.DiscordTools.executeMod] still re-verify authority live
 * against JDA before acting.
 *
 * [personalitySummary] is a short PT-BR description ("O usuário gosta de X, não quer Y")
 * generated by [com.cyrene.ai.PersonalitySummarizer]. Created on first contact and
 * re-summarized every N exchanges so the bot can build a relationship with the user
 * over time without re-asking the LLM to introspect via tools each turn.
 */
@Entity
@Table(name = "users_info")
class UserInfo(

    @Column(name = "user_id", nullable = false)
    var userId: String,

    @Column(name = "guild_id", nullable = false)
    var guildId: String,

    @Column(name = "effective_name", nullable = false)
    var effectiveName: String,

    @Column(name = "highest_role_id")
    var highestRoleId: String? = null,

    @Column(name = "highest_role_name")
    var highestRoleName: String? = null,

    @Column(name = "administrator", nullable = false)
    var administrator: Boolean = false,

    @Column(name = "kick_members", nullable = false)
    var kickMembers: Boolean = false,

    @Column(name = "ban_members", nullable = false)
    var banMembers: Boolean = false,

    @Column(name = "moderate_members", nullable = false)
    var moderateMembers: Boolean = false,

    @Column(name = "manage_messages", nullable = false)
    var manageMessages: Boolean = false,

    @Column(name = "manage_channel", nullable = false)
    var manageChannel: Boolean = false,

    @Column(name = "manage_guild", nullable = false)
    var manageGuild: Boolean = false,

    @Column(name = "personality_summary", columnDefinition = "TEXT")
    var personalitySummary: String? = null,

    @Column(name = "exchanges_count", nullable = false)
    var exchangesCount: Int = 0,

    @Column(name = "last_refreshed_at", nullable = false)
    var lastRefreshedAt: OffsetDateTime = OffsetDateTime.now(),

    @Column(name = "created_at", nullable = false)
    var createdAt: OffsetDateTime = OffsetDateTime.now(),

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null,
)
