package com.cyrene.conversation

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.Table
import java.time.OffsetDateTime

/**
 * Persisted memory the bot keeps about a single Discord user (global — not per-guild).
 *
 * Privacy model: memory is OPT-IN. A row is created on first contact with [memoryEnabled]
 * = false (it exists only to hold the opt-in flag); the user turns it on via the `/memoria`
 * command ([com.cyrene.discord.command.MemoryCommand]). [memoryEnabled] gates everything —
 * while false, no personality summary is generated, no [UserFact]s are saved, and the prompt
 * carries only live identity data (name/role/permissions) read fresh from JDA, never persisted.
 *
 * [personalitySummary] is a short PT-BR description generated by
 * [com.cyrene.ai.PersonalitySummarizer] and re-summarized every N exchanges. Discrete,
 * verbatim facts live in [UserFact] instead so they are not blurred by re-summarization.
 *
 * Name, role and permissions are deliberately NOT stored here: they vary per guild and are
 * cheap to read live from the JDA Member, so persisting them only created duplication.
 */
@Entity
@Table(name = "perfil_usuario")
class UserProfile(

    @Column(name = "usuario_id", nullable = false, unique = true)
    var userId: String,

    @Column(name = "memoria_ativa", nullable = false)
    var memoryEnabled: Boolean = false,

    @Column(name = "resumo_personalidade", columnDefinition = "TEXT")
    var personalitySummary: String? = null,

    @Column(name = "contagem_interacoes", nullable = false)
    var exchangesCount: Int = 0,

    @Column(name = "criado_em", nullable = false)
    var createdAt: OffsetDateTime = OffsetDateTime.now(),

    @Column(name = "atualizado_em", nullable = false)
    var updatedAt: OffsetDateTime = OffsetDateTime.now(),

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null,
)
